//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMPMSDVC.centraloGer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="centraloGer.IConexSuc")]
    public interface IConexSuc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConexSuc/HolaMundo", ReplyAction="http://tempuri.org/IConexSuc/HolaMundoResponse")]
        string HolaMundo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConexSuc/SincronizarDvTienda", ReplyAction="http://tempuri.org/IConexSuc/SincronizarDvTiendaResponse")]
        string SincronizarDvTienda();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConexSuc/ReportarHallazgos", ReplyAction="http://tempuri.org/IConexSuc/ReportarHallazgosResponse")]
        bool ReportarHallazgos(string HallazgosDV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConexSuc/ComunicacionConTienda", ReplyAction="http://tempuri.org/IConexSuc/ComunicacionConTiendaResponse")]
        bool ComunicacionConTienda();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConexSuc/RestaurarDvTienda", ReplyAction="http://tempuri.org/IConexSuc/RestaurarDvTiendaResponse")]
        bool RestaurarDvTienda(string Tienda, string NombreDV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConexSuc/MonitoreoDV", ReplyAction="http://tempuri.org/IConexSuc/MonitoreoDVResponse")]
        bool MonitoreoDV();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConexSucChannel : DMPMSDVC.centraloGer.IConexSuc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConexSucClient : System.ServiceModel.ClientBase<DMPMSDVC.centraloGer.IConexSuc>, DMPMSDVC.centraloGer.IConexSuc {
        
        public ConexSucClient() {
        }
        
        public ConexSucClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConexSucClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConexSucClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConexSucClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HolaMundo() {
            return base.Channel.HolaMundo();
        }
        
        public string SincronizarDvTienda() {
            return base.Channel.SincronizarDvTienda();
        }
        
        public bool ReportarHallazgos(string HallazgosDV) {
            return base.Channel.ReportarHallazgos(HallazgosDV);
        }
        
        public bool ComunicacionConTienda() {
            return base.Channel.ComunicacionConTienda();
        }
        
        public bool RestaurarDvTienda(string Tienda, string NombreDV) {
            return base.Channel.RestaurarDvTienda(Tienda, NombreDV);
        }
        
        public bool MonitoreoDV() {
            return base.Channel.MonitoreoDV();
        }
    }
}
