//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMPMSDVC.central {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="central.IConexSuc")]
    public interface IConexSuc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConexSuc/EntregaRepHallazgos", ReplyAction="http://tempuri.org/IConexSuc/EntregaRepHallazgosResponse")]
        bool EntregaRepHallazgos(string ContXml, int Suc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConexSuc/ConfigOrqAct", ReplyAction="http://tempuri.org/IConexSuc/ConfigOrqActResponse")]
        string ConfigOrqAct(int Suc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConexSuc/SincronizarInfoMtr", ReplyAction="http://tempuri.org/IConexSuc/SincronizarInfoMtrResponse")]
        string SincronizarInfoMtr(int Suc, string FechaCambios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConexSuc/ReportaEstacTrab", ReplyAction="http://tempuri.org/IConexSuc/ReportaEstacTrabResponse")]
        bool ReportaEstacTrab(string WsCadena, int Suc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConexSuc/SolReportarHallazgoDemanda", ReplyAction="http://tempuri.org/IConexSuc/SolReportarHallazgoDemandaResponse")]
        string SolReportarHallazgoDemanda(string ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConexSuc/SolZip", ReplyAction="http://tempuri.org/IConexSuc/SolZipResponse")]
        string SolZip(string ip, string ruta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConexSuc/CrearCatalogoDVs", ReplyAction="http://tempuri.org/IConexSuc/CrearCatalogoDVsResponse")]
        string CrearCatalogoDVs();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConexSucChannel : DMPMSDVC.central.IConexSuc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConexSucClient : System.ServiceModel.ClientBase<DMPMSDVC.central.IConexSuc>, DMPMSDVC.central.IConexSuc {
        
        public ConexSucClient() {
        }
        
        public ConexSucClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConexSucClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConexSucClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConexSucClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool EntregaRepHallazgos(string ContXml, int Suc) {
            return base.Channel.EntregaRepHallazgos(ContXml, Suc);
        }
        
        public string ConfigOrqAct(int Suc) {
            return base.Channel.ConfigOrqAct(Suc);
        }
        
        public string SincronizarInfoMtr(int Suc, string FechaCambios) {
            return base.Channel.SincronizarInfoMtr(Suc, FechaCambios);
        }
        
        public bool ReportaEstacTrab(string WsCadena, int Suc) {
            return base.Channel.ReportaEstacTrab(WsCadena, Suc);
        }
        
        public string SolReportarHallazgoDemanda(string ip) {
            return base.Channel.SolReportarHallazgoDemanda(ip);
        }
        
        public string SolZip(string ip, string ruta) {
            return base.Channel.SolZip(ip, ruta);
        }
        
        public string CrearCatalogoDVs() {
            return base.Channel.CrearCatalogoDVs();
        }
    }
}
