//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrquestadorCentralWs.ConexionTiendas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConexionTiendas.IConexCentral")]
    public interface IConexCentral {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConexCentral/SolReportarHallazgos", ReplyAction="http://tempuri.org/IConexCentral/SolReportarHallazgosResponse")]
        string SolReportarHallazgos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConexCentral/SolMonitoreaDV", ReplyAction="http://tempuri.org/IConexCentral/SolMonitoreaDVResponse")]
        string SolMonitoreaDV(string IpWorkstation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConexCentral/SolReiniciaCfg", ReplyAction="http://tempuri.org/IConexCentral/SolReiniciaCfgResponse")]
        bool SolReiniciaCfg();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConexCentral/AnyforToWork", ReplyAction="http://tempuri.org/IConexCentral/AnyforToWorkResponse")]
        string AnyforToWork(string ruta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConexCentral/Test", ReplyAction="http://tempuri.org/IConexCentral/TestResponse")]
        bool Test();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConexCentralChannel : OrquestadorCentralWs.ConexionTiendas.IConexCentral, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConexCentralClient : System.ServiceModel.ClientBase<OrquestadorCentralWs.ConexionTiendas.IConexCentral>, OrquestadorCentralWs.ConexionTiendas.IConexCentral {
        
        public ConexCentralClient() {
        }
        
        public ConexCentralClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConexCentralClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConexCentralClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConexCentralClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SolReportarHallazgos() {
            return base.Channel.SolReportarHallazgos();
        }
        
        public string SolMonitoreaDV(string IpWorkstation) {
            return base.Channel.SolMonitoreaDV(IpWorkstation);
        }
        
        public bool SolReiniciaCfg() {
            return base.Channel.SolReiniciaCfg();
        }
        
        public string AnyforToWork(string ruta) {
            return base.Channel.AnyforToWork(ruta);
        }
        
        public bool Test() {
            return base.Channel.Test();
        }
    }
}
